/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportCirclesRouteImport } from './routes/support-circles'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as HomeSafetyAuditRouteImport } from './routes/home-safety-audit'
import { Route as DailyCareGuideRouteImport } from './routes/daily-care-guide'
import { Route as CrisisProtocolRouteImport } from './routes/crisis-protocol'
import { Route as CommunicationTipsRouteImport } from './routes/communication-tips'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SupportCirclesRoute = SupportCirclesRouteImport.update({
  id: '/support-circles',
  path: '/support-circles',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSafetyAuditRoute = HomeSafetyAuditRouteImport.update({
  id: '/home-safety-audit',
  path: '/home-safety-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyCareGuideRoute = DailyCareGuideRouteImport.update({
  id: '/daily-care-guide',
  path: '/daily-care-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisisProtocolRoute = CrisisProtocolRouteImport.update({
  id: '/crisis-protocol',
  path: '/crisis-protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationTipsRoute = CommunicationTipsRouteImport.update({
  id: '/communication-tips',
  path: '/communication-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/communication-tips': typeof CommunicationTipsRoute
  '/crisis-protocol': typeof CrisisProtocolRoute
  '/daily-care-guide': typeof DailyCareGuideRoute
  '/home-safety-audit': typeof HomeSafetyAuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support-circles': typeof SupportCirclesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/communication-tips': typeof CommunicationTipsRoute
  '/crisis-protocol': typeof CrisisProtocolRoute
  '/daily-care-guide': typeof DailyCareGuideRoute
  '/home-safety-audit': typeof HomeSafetyAuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support-circles': typeof SupportCirclesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/communication-tips': typeof CommunicationTipsRoute
  '/crisis-protocol': typeof CrisisProtocolRoute
  '/daily-care-guide': typeof DailyCareGuideRoute
  '/home-safety-audit': typeof HomeSafetyAuditRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support-circles': typeof SupportCirclesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/communication-tips'
    | '/crisis-protocol'
    | '/daily-care-guide'
    | '/home-safety-audit'
    | '/sitemap.xml'
    | '/support-circles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/communication-tips'
    | '/crisis-protocol'
    | '/daily-care-guide'
    | '/home-safety-audit'
    | '/sitemap.xml'
    | '/support-circles'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/communication-tips'
    | '/crisis-protocol'
    | '/daily-care-guide'
    | '/home-safety-audit'
    | '/sitemap.xml'
    | '/support-circles'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunicationTipsRoute: typeof CommunicationTipsRoute
  CrisisProtocolRoute: typeof CrisisProtocolRoute
  DailyCareGuideRoute: typeof DailyCareGuideRoute
  HomeSafetyAuditRoute: typeof HomeSafetyAuditRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportCirclesRoute: typeof SupportCirclesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support-circles': {
      id: '/support-circles'
      path: '/support-circles'
      fullPath: '/support-circles'
      preLoaderRoute: typeof SupportCirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-safety-audit': {
      id: '/home-safety-audit'
      path: '/home-safety-audit'
      fullPath: '/home-safety-audit'
      preLoaderRoute: typeof HomeSafetyAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-care-guide': {
      id: '/daily-care-guide'
      path: '/daily-care-guide'
      fullPath: '/daily-care-guide'
      preLoaderRoute: typeof DailyCareGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crisis-protocol': {
      id: '/crisis-protocol'
      path: '/crisis-protocol'
      fullPath: '/crisis-protocol'
      preLoaderRoute: typeof CrisisProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communication-tips': {
      id: '/communication-tips'
      path: '/communication-tips'
      fullPath: '/communication-tips'
      preLoaderRoute: typeof CommunicationTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunicationTipsRoute: CommunicationTipsRoute,
  CrisisProtocolRoute: CrisisProtocolRoute,
  DailyCareGuideRoute: DailyCareGuideRoute,
  HomeSafetyAuditRoute: HomeSafetyAuditRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportCirclesRoute: SupportCirclesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
